#!/bin/bash
# XKSH808 Promo Post Generator
# Usage: run with offer name as argument e.g. "Starter Pack"

source /app/.agents/.env

OFFER="${1:-Starter Pack}"

# Map offer details
case "$OFFER" in
  "Starter Pack")
    PRICE="297"
    DESC="Core web + SEO starter package — custom site, local SEO setup, Google Business optimization"
    HOOK="Your competitors are showing up on Google. You're not."
    ;;
  "Pro Build")
    PRICE="497"
    DESC="Full funnel + booking automation — site, SEO, contact forms, automated follow-up, booking system"
    HOOK="Stop losing jobs to guys with worse work but better websites."
    ;;
  "KK OS Setup")
    PRICE="997"
    DESC="Full Kontrold Khaos OS deployment — AI-powered lead engine, automated outreach, client management system"
    HOOK="What if your business ran itself while you were on the job?"
    ;;
  "Souper Agent Bot")
    PRICE="197"
    DESC="AI chatbot for your website — answers questions, captures leads, books appointments 24/7"
    HOOK="Your website is losing leads every night while you sleep."
    ;;
  "Site Refresh")
    PRICE="299"
    DESC="Mobile-first site refresh — click-to-call hero, reviews featured, Netlify deploy, 48hr turnaround"
    HOOK="Slow website = lost jobs. Period."
    ;;
  *)
    PRICE="297"
    DESC="$OFFER — XKSH808 digital services for Hawaii local businesses"
    HOOK="Hawaii businesses need better digital presence."
    ;;
esac

echo "🔥 XKSH808 PROMO GENERATOR — $OFFER (\$$PRICE)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Generate all 4 formats via Groq
curl -s -X POST "https://api.groq.com/openai/v1/chat/completions" \
  -H "Authorization: Bearer $GROQ_API_KEY" \
  -H "Content-Type: application/json" \
  -d "{
    \"model\": \"llama-3.3-70b-versatile\",
    \"messages\": [{
      \"role\": \"system\",
      \"content\": \"You are the marketing voice for XKSH808, a digital services company in Hawaii. You write hyper-local, punchy promo content for small trade businesses (plumbers, cleaners, HVAC, landscapers, auto shops). Tone: local Hawaii, direct, zero fluff, conversational. No corporate speak. No AI mentions. Sound like a local who gets results.\"
    },{
      \"role\": \"user\",
      \"content\": \"Generate promo content for this offer:\\n\\nOffer: $OFFER\\nPrice: \\\$$PRICE\\nDescription: $DESC\\nCore hook: $HOOK\\nTarget: Hawaii local trade businesses (plumbers, cleaners, HVAC, landscapers, auto shops, restaurants)\\nBrand: XKSH808 Digital Services Hawaii\\nCash App: \\\$xksh808dsh\\n\\nGenerate ALL 4 formats with clear labels:\\n\\n1. INSTAGRAM CAPTION — Hook line, 3-4 value sentences, CTA with Cash App, 8-10 Hawaii-relevant hashtags\\n2. TIKTOK HOOK — First 3 seconds only (1-2 punchy sentences that stop the scroll)\\n3. COLD DM SCRIPT — Short IG or WhatsApp DM, personalized for a plumber or cleaner, under 5 sentences, ends with a soft CTA\\n4. STORY TEXT — 1-2 lines max for an IG/WhatsApp story text overlay\\n\\nKeep each section clearly separated with the label.\"
    }],
    \"temperature\": 0.75,
    \"max_tokens\": 900
  }" | python3 -c "
import sys, json
d = json.load(sys.stdin)
if 'choices' in d:
    print(d['choices'][0]['message']['content'])
else:
    print('ERROR:', d.get('error',{}).get('message','Groq call failed'))
"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Generated by XKSH808 Ghost Engine | Cash App: \$xksh808dsh"
